name: "Merge release"
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        working-directory: Assets/WavEffector
        run: |
          npm install -g --save-dev commitinit
          npm install -g --save-dev husky

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
